version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phone-manager
    ports:
      - "127.0.0.1:6060:6060"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - server-network
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/data/db_data:/data/db
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
